# Generated by Django 5.0 on 2024-01-01 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='')),
                ('name', models.CharField(max_length=150, verbose_name='')),
                ('email', models.EmailField(max_length=254, verbose_name='')),
                ('number', models.IntegerField(verbose_name='')),
                ('adress', models.TextField(verbose_name='')),
            ],
        ),
    ]
