# Generated by Django 5.0 on 2024-01-02 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_user_password'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='person',
        ),
    ]
