# Generated by Django 5.0 on 2024-01-02 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_alter_person_options_alter_person_managers_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='person',
        ),
    ]
