# Generated by Django 5.0 on 2024-01-29 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_dp',
            field=models.ImageField(null=True, upload_to='user_dp/'),
        ),
    ]
