# Generated by Django 5.0 on 2024-01-29 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_user_user_dp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_dp',
            field=models.ImageField(default=-1222, upload_to='media/user_dp/'),
            preserve_default=False,
        ),
    ]
