# Generated by Django 5.0 on 2024-01-29 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_alter_user_user_dp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.CreateModel(
            name='user_address',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address1', models.TextField(null=True)),
                ('address2', models.TextField(null=True)),
                ('address3', models.TextField(null=True)),
                ('address4', models.TextField(null=True)),
                ('address5', models.TextField(null=True)),
                ('address6', models.TextField(null=True)),
                ('address7', models.TextField(null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_address', to='login.user')),
            ],
        ),
    ]
