# Generated by Django 5.0 on 2024-02-05 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_remove_user_address_user_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_dp',
            field=models.ImageField(default='media/user_dp/user.jpg', upload_to='media/user_dp/'),
        ),
    ]
