# Generated by Django 5.0 on 2024-02-06 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0016_alter_user_user_dp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_address',
            name='address1',
        ),
        migrations.RemoveField(
            model_name='user_address',
            name='address2',
        ),
        migrations.RemoveField(
            model_name='user_address',
            name='address3',
        ),
        migrations.RemoveField(
            model_name='user_address',
            name='address4',
        ),
        migrations.RemoveField(
            model_name='user_address',
            name='address5',
        ),
        migrations.RemoveField(
            model_name='user_address',
            name='address6',
        ),
        migrations.RemoveField(
            model_name='user_address',
            name='address7',
        ),
        migrations.RemoveField(
            model_name='user_address',
            name='user_id',
        ),
        migrations.AddField(
            model_name='user',
            name='current_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='address', to='login.user_address'),
        ),
    ]
