# Generated by Django 5.0 on 2024-02-07 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0018_user_address_call_number_user_address_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_address',
            old_name='picode',
            new_name='pincode',
        ),
    ]
