# Generated by Django 5.0 on 2024-02-20 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0019_rename_picode_user_address_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='number',
            field=models.BigIntegerField(),
        ),
    ]
