# Generated by Django 5.0 on 2024-02-21 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0021_alter_user_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_address',
            name='call_number',
            field=models.BigIntegerField(),
        ),
    ]
