# Generated by Django 5.0 on 2024-02-06 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='book_quantity',
            field=models.IntegerField(null=True),
        ),
    ]
