# Generated by Django 5.0 on 2024-01-12 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyAdminCategory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('category_description', models.TextField()),
                ('offer', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='myvariant',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('phone_number', models.IntegerField()),
                ('prodect_name', models.CharField(max_length=50)),
                ('order_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='unlist_prodect',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('price', models.IntegerField()),
                ('prodect_name', models.CharField()),
                ('category', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('quantity', models.IntegerField()),
                ('variant', models.CharField(max_length=50)),
                ('prodect_image1', models.ImageField(upload_to='image/unlist')),
                ('prodect_image2', models.ImageField(upload_to='image/unlist')),
                ('prodect_image3', models.ImageField(upload_to='image/unlist')),
            ],
        ),
        migrations.CreateModel(
            name='prodects',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('price', models.IntegerField()),
                ('prodect_name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('quantity', models.IntegerField()),
                ('offer', models.IntegerField(null=True)),
                ('prodect_image1', models.ImageField(upload_to='image/')),
                ('prodect_image2', models.ImageField(upload_to='image/')),
                ('prodect_image3', models.ImageField(upload_to='image/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_products', to='my_admin.myadmincategory')),
                ('variant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variant_products', to='my_admin.myvariant')),
            ],
        ),
    ]