# Generated by Django 5.0 on 2024-01-12 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='myprodects',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('price', models.IntegerField()),
                ('prodect_name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('quantity', models.IntegerField()),
                ('offer', models.IntegerField(null=True)),
                ('prodect_image1', models.ImageField(upload_to='image/')),
                ('prodect_image2', models.ImageField(upload_to='image/')),
                ('prodect_image3', models.ImageField(upload_to='image/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_products', to='my_admin.myadmincategory')),
                ('variant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variant_products', to='my_admin.myvariant')),
            ],
        ),
        migrations.DeleteModel(
            name='prodects',
        ),
    ]
