# Generated by Django 5.0 on 2024-01-12 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_admin', '0002_myprodects_delete_prodects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprodects',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_products', to='my_admin.myadmincategory'),
        ),
    ]
