# Generated by Django 5.0 on 2024-01-13 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_admin', '0003_alter_myprodects_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='myadmincategory',
            name='category_image',
            field=models.ImageField(default=1, upload_to='image/'),
            preserve_default=False,
        ),
    ]
