# Generated by Django 5.0 on 2024-01-13 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_admin', '0004_myadmincategory_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myadmincategory',
            name='category_image',
            field=models.ImageField(upload_to='category_image/'),
        ),
    ]
