# Generated by Django 5.0 on 2024-01-13 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_admin', '0006_remove_myadmincategory_id_remove_myvariant_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminCategory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('category_description', models.TextField()),
                ('offer', models.IntegerField()),
                ('category_image', models.ImageField(upload_to='category_image/')),
            ],
        ),
        migrations.CreateModel(
            name='variant',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='myprodects',
            name='category',
        ),
        migrations.RemoveField(
            model_name='myprodects',
            name='variant',
        ),
        migrations.CreateModel(
            name='myprodect',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('price', models.IntegerField()),
                ('prodect_name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('quantity', models.IntegerField()),
                ('offer', models.IntegerField(null=True)),
                ('prodect_image1', models.ImageField(upload_to='image/')),
                ('prodect_image2', models.ImageField(upload_to='image/')),
                ('prodect_image3', models.ImageField(upload_to='image/')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_products', to='my_admin.admincategory')),
                ('variant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variant_products', to='my_admin.variant')),
            ],
        ),
        migrations.DeleteModel(
            name='MyAdminCategory',
        ),
        migrations.DeleteModel(
            name='myprodects',
        ),
        migrations.DeleteModel(
            name='myvariant',
        ),
    ]
