# Generated by Django 5.0 on 2024-01-13 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_admin', '0007_admincategory_variant_remove_myprodects_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='name',
        ),
        migrations.AddField(
            model_name='variant',
            name='variant_name',
            field=models.CharField(default='first grade', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
