# Generated by Django 5.0 on 2024-01-13 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_admin', '0008_remove_variant_name_variant_variant_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='myvariant',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('variant_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='myprodect',
            name='variant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variant_products', to='my_admin.myvariant'),
        ),
        migrations.DeleteModel(
            name='variant',
        ),
    ]
