# Generated by Django 5.0 on 2024-01-13 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_admin', '0009_myvariant_alter_myprodect_variant_delete_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unlist_prodect',
            name='category',
            field=models.CharField(max_length=50),
        ),
    ]
