# Generated by Django 5.0 on 2024-01-20 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_admin', '0011_alter_myprodect_prodect_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='myprodect',
            name='status',
            field=models.CharField(default='list', max_length=10),
        ),
    ]
