# Generated by Django 5.0 on 2024-02-06 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_admin', '0012_myprodect_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='unlist_prodect',
        ),
    ]
