# Generated by Django 5.0 on 2024-02-19 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_admin', '0013_delete_unlist_prodect'),
    ]

    operations = [
        migrations.AddField(
            model_name='admincategory',
            name='status',
            field=models.CharField(default='list', max_length=50),
        ),
        migrations.AddField(
            model_name='myvariant',
            name='status',
            field=models.CharField(default='list', max_length=50),
        ),
    ]
