# Generated by Django 5.0 on 2024-02-19 15:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_expect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='expect',
            field=models.DateField(default=datetime.datetime(2024, 2, 25, 15, 30, 3, 630683, tzinfo=datetime.timezone.utc)),
        ),
    ]
