# Generated by Django 5.0 on 2024-02-20 05:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_expect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='expect',
            field=models.DateField(default=datetime.datetime(2024, 2, 26, 5, 29, 44, 906940, tzinfo=datetime.timezone.utc)),
        ),
    ]
